# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbbc53f0bfedb58c139f29043465d2087f88de2339f65f413dc5ba0471a450e5c05f14ca7fcd1711dc7f24e513e19722faeb4af6cfc3788c95667ef86625ade0

test:
  secret_key_base: 36e43cca2f8001a4ae8fa6c79793b6122347da04fcab02e3ac416e275d5aa214858e57de94e86300b09c4e43334c83b91ab2dd377f82cd8c1180f47fe20c5cbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
